version: '3.0' # specify docker-compose version

# Define the services (i.e. containers) to be run
services:
  contact-book-server:
    build:
      context: .                          # directory of the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - contact-book-database             # link this service to the database service
    environment:
      DB_HOST: contact-book-database    # name of the db container
    volumes:
      - /Users/davidvargas/Workspace/ngrx-sandbox/contact-book-server:/usr/server
      - /usr/server/node_modules
      - /Users/davidvargas/Workspace/ngrx-sandbox/contact-book-client:/usr/client
      - /usr/client/node_modules
      - /Users/davidvargas/Workspace/ngrx-sandbox/out/log/server:/usr/server/log
      - /Users/davidvargas/Workspace/ngrx-sandbox/out/log/npm:/root/.npm/_logs

  contact-book-database:
          image: mongo:3.4.18-jessie            # image to build container from
          ports:
            - "27017:27017"
          restart: always
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
          volumes:
            - /Users/davidvargas/Workspace/ngrx-sandbox/contact-book-db:/data/db
            - /Users/davidvargas/Workspace/ngrx-sandbox/out/log/mongodb:/var/log/mongodb/
            - /Users/davidvargas/Workspace/ngrx-sandbox/out/db_dump:/usr/db_dump
